### PR TITLE
Supporting (static) setup of V8 custom flags and ICU data file

### PR DESCRIPTION
**Pull request by dbo**

### CODE REVIEW

**Comment by irbull** [comment]
Thanks Daniel. I will look at these when I land.

**Comment by dbo** [comment]
@irbull Hi Ian, what's up with this one? Although bit-rotten already, any reason why ICU and custom flags support shouldn't land?

**Comment by dbo** [comment]
Ian?

**Comment by irbull** [comment]
Sorry, no reason why this shouldn't land. I've put some custom flag stuff in V8.setFlags(), so I need to pull this apart. I've been working to redo the build -- to build on node rather than straight V8. The reason is twofold, having node support in J2V8 is cool, and node is actually easier to build than V8 (and it includes V8). This second part was true for Linux / Mac and I just (2 minutes ago) got this working on Windows.

I'll be pushing out a release now that all this is in place. I will grab this pull request and see if I can get the remaining parts in.

**Comment by midzelis** [comment]
@irbull - I use a MacPro as my primary desktop. I'd be happy to set up some jenkins servers to run automated multi-arch build. I can run windows/linux in vm's and cover at least windows/mac/linux.

**Pull request closed without merging**
