### PR TITLE
add method to get node version

### PR DESCRIPTION
**Pull request by muthu90ec**
Add public method to get node version

### CODE REVIEW

**Comment by irbull** [comment]
Sorry, I didn't see this PR and I implemented this yesterday. However, I like your version a bit better since it caches the Version value. I am going to try and incorporate this. Thanks!

**Comment by muthu90ec** [comment]
Thanks

**Comment by irbull** [comment]
An interesting side note to this. `process.version` return `vX.Y.Z` whereas `process.versions.node` return `X.Y.Z`. I don't think one is more right than the other. I'm going to with `process.versions.node` since that's what you had in this PR.

I have made a few small modifications. 
 - I have changed the method name from `nodeVersion` to `getNodeVersion`
 - I have changed the uninitialized value to null (instead of empty string).
 - I have extracted the string constants `versions` and `node`

This is coming to master shortly. Thanks @muthu90ec

**Comment by irbull** [comment]
This RP is now merged. See 9942399b3c250f777f1297a51c5fcb362ef3b387. I need to close this manually, but it has been accepted. Thanks!!!

**Pull request closed without merging**
