### PR TITLE
Upgrade Node to v7.4.0, Android support

### PR DESCRIPTION
**Pull request by KnownUnown**
This pull upgrades J2V8 to v7.4.0 and adds Android support for the Node runtime.

### CODE REVIEW

**Comment by irbull** [comment]
@KnownUnown Did you have any troubles with `FrameTest#testGetSourceLocation`? Everything else seems to pass, but that test is giving me some problems. It looks like like the Frame has key called `script`, but fetching it returns null.

**Comment by irbull** [comment]
@KnownUnown Sorry, I saw your comment on #237, it appears you have the same problem as me. That's ok, I think I can fix that. However, I have a bigger issue. It appears you are only building the library for arm, but you link against node --and I don't see where you specified an ARM build for node. Do you have node built for both arm and x86? We have consumers on both platforms.

**Comment by KnownUnown** [comment]
Oops, forgot to include my Android build process >.> The build is somewhat convoluted and requires Docker. Where do you think I should put the Dockerfile?

**Comment by irbull** [comment]
Cool. I'm using a Docker build as well for it. Is it just a dockerfile, or
do you have additional scripts to manage the docker build and execution?
Feel free to include it in the change-set. Maybe just make a directory
called docker. we can flush out the details together.

Thanks!

**Comment by KnownUnown** [comment]
Alright, the latest commit provides the necessary tools and instructions to build on Android, @irbull. Sorry for the wait. Let me know if you need anything else :)

**Comment by irbull** [comment]
This is great! Thank-you so much.
A few quick questions:
1. You mentioned in #237 that you had to patch node? I see some env variables related to `fPIC`, but did you actually need to patch node in the end?
2. Have you tried to build this for x86? I'm trying right now (I modified the `Dockerfile` and the build is still running). I'm currently getting `incompatible target` but I'm likely missing a few configuration changes.
3. I don't have much to offer, but I do have some J2V8 stickers if you're interested. If you forward me a mailing address (my github username at gmail) I'll send some stickers to you. Thanks so much for all this work!

**Comment by KnownUnown** [comment]
No problem!
To answer your questions:

1. I ended up not needing to patch node. It was a workaround for the env variables not working (still not sure why it didn't work in the first place), but they apply `fPIC` properly now.
2. Hmm, need to try that...assuming you're referring to Android x86, I'd imagine all that needs to happen is swapping out `arm` with `ia32`, but you've probably already did that. Will investigate further.
3. No problem, just giving back to the community :) Been sitting on this for a while, just never had time to upstream it. Stickers are more than enough, thanks!

**Comment by irbull** [comment]
Cool! I have it running on an X86 simulator. I haven't tried the arm builds, yet, but they build fine so :crossed_fingers:. 

Regarding the x86 builds, I used x86 (not ia32) and they build, but they produce a library that's > 30mb. It used to be around 10. The arm build is around 10mb. Let me try ia32 and see if that changes anything.

**Comment by irbull** [comment]
I have built and pushed out a SNAPSHOT based on this work.
https://oss.sonatype.org/content/repositories/snapshots/com/eclipsesource/j2v8/j2v8/4.7.0-SNAPSHOT/

The snapshot was built slightly differently from this. First, I did not include `node`. The `aar` was getting big, and I wanted to see what sort of effect not linking to node would have. I also removed ICU. Without node and ICU, we cut about 8MB from the `aar`. Maybe we should create a few different configurations.
Second, I used minSDK 17 instead of 19 (the PR has 19). I would like to target a lower SDK. 

I am going to merge this PR, and then push a few more small changes that I made. Thanks again @KnownUnown!

**Comment by irbull** [comment]
I merged it manually, See 8663349080e673fe93db3f2954a1b047bf991ecf.

**Comment by bighenry-lai** [comment]
I want to test it with node. Do you have snapshots build with node?

**Pull request closed without merging**
